parameters:
    knp.twig_explorer.twig.string_extension.class: Knp\TwigExplorer\Twig\StringExtension
    knp.twig_explorer.twig.extension_container.class: Knp\TwigExplorer\Twig\ExtensionContainer
    knp.twig_explorer.name.resolver_registry.class: Knp\TwigExplorer\Name\ResolverRegistry
    knp.twig_explorer.name.by_key_resolver.class: Knp\TwigExplorer\Name\ByKeyResolver
    knp.twig_explorer.name.by_name_resolver.class: Knp\TwigExplorer\Name\ByNameResolver
    knp.twig_explorer.name.token_parser_resolver.class: Knp\TwigExplorer\Name\TokenParserResolver

services:
    knp.twig_explorer.twig.string_extension:
        class: %knp.twig_explorer.twig.string_extension.class%
        tags:
            - { name: twig.extension }

    knp.twig_explorer.twig.extension_container:
        class: %knp.twig_explorer.twig.extension_container.class%

    knp.twig_explorer.name.resolver_registry:
        class: %knp.twig_explorer.name.resolver_registry.class%

    knp.twig_explorer.name.by_key_resolver:
        class: %knp.twig_explorer.name.by_key_resolver.class%
        tags:
            - { name: knp.twig_explorer.name_resolver }

    knp.twig_explorer.name.by_name_resolver:
        class: %knp.twig_explorer.name.by_name_resolver.class%
        tags:
            - { name: knp.twig_explorer.name_resolver }

    knp.twig_explorer.name.token_parser_resolver:
        class: %knp.twig_explorer.name.token_parser_resolver.class%
        tags:
            - { name: knp.twig_explorer.name_resolver }
