parameters:
    knp.twig_explorer.twig.string_extension.class: Knp\TwigExplorer\Twig\StringExtension
    knp.twig_explorer.twig.extension_container.class: Knp\TwigExplorer\Twig\ExtensionContainer
    knp.twig_explorer.name.resolver_registry.class: Knp\TwigExplorer\Name\ResolverRegistry
    knp.twig_explorer.name.simple_filter_resolver.class: Knp\TwigExplorer\Name\SimpleFilterResolver
    knp.twig_explorer.name.filter_method_resolver.class: Knp\TwigExplorer\Name\FilterMethodResolver
    knp.twig_explorer.name.trans_token_resolver.class: Knp\TwigExplorer\Name\TransTokenResolver

services:
    knp.twig_explorer.twig.string_extension:
        class: %knp.twig_explorer.twig.string_extension.class%
        tags:
            - { name: twig.extension }

    knp.twig_explorer.twig.extension_container:
        class: %knp.twig_explorer.twig.extension_container.class%

    knp.twig_explorer.name.resolver_registry:
        class: %knp.twig_explorer.name.resolver_registry.class%

    knp.twig_explorer.name.simple_filter_resolver:
        class: %knp.twig_explorer.name.simple_filter_resolver.class%
        tags:
            - { name: knp.twig_explorer.name_resolver }

    knp.twig_explorer.name.filter_method_resolver:
        class: %knp.twig_explorer.name.filter_method_resolver.class%
        tags:
            - { name: knp.twig_explorer.name_resolver }

    knp.twig_explorer.name.trans_token_resolver:
        class: %knp.twig_explorer.name.trans_token_resolver.class%
        tags:
            - { name: knp.twig_explorer.name_resolver }
